basePath: /
host: localhost:8080
info:
  contact:
    name: Joseph Beck
  description: a realtime chatting and calling app
  license:
    name: MIT
    url: https://opensource.org/license/mit/
  title: Chit Chat
  version: "0.1"
paths:
  /api/v1/login:
    get:
      description: Once "logged in" a users auth token will last for one hour
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Login in a user and create a session
      tags:
      - users
swagger: "2.0"
